# Generated by Django 3.2.3 on 2021-05-21 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 21, 15, 50, 49, 796480, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
